services:
  pip_demo:
    build: pip_demo

  uv_demo:
    build: uv_demo

  uv_lib_demo:
    build: uv_lib_demo
    ports:
      - "8888:8888"

  conda_demo:
    build: conda_demo

  pixi_demo:
    build: pixi_demo

  pixi_lib_demo:
    build: pixi_lib_demo
    ports:
      - "8889:8889"
